export * from '@/views/ErrorView';
export * from '@/views/HomeView';
export * from '@/views/CreditsView';
export * from '@/views/movies/MovieView';
export * from '@/views/movies/MoviesView';
export * from '@/views/movies/MovieCategoriesView';
// export * from '@/views/movies/NowPlayingView';
export * from '@/views/ReviewsView';
export * from '@/views/TrendingView';
export * from '@/views/TelevisionsView';
export * from '@/views/SearchView';
export * from '@/views/PersonView';
